# Generated by Django 5.1 on 2024-09-12 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['user'], 'verbose_name_plural': 'Автор'},
        ),
    ]
